### ISSUE TITLE
Croodle: Poll title requires at least one char

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#100]
![croodleonechar](https://cloud.githubusercontent.com/assets/11966684/15945935/e0796a36-2e94-11e6-8606-79024951e531.png)

As you can see in the picture the requirement is satisfied, because "at least 1" means >= 1. So either allow one character titles or change the error message.

tested with latest dev version

**Comment by rugk** [comment]
You fixed it, but now the displayed text does not make sense anymore:
![minimumchars](https://cloud.githubusercontent.com/assets/11966684/16241814/b5db4c4a-37ef-11e6-9a78-3950e5fec369.png)

> minimum is characters

(similar text in the translations)

Well, right. I think we all wanted to put in characters there - as a minimum! :laughing:

**Comment by jelhan** [comment]
a76d5cc9a138447da37edbdc5b00dd9be7084e43 is not part of alpha5. I guessed you tested against that one. Will be included in next pre-release.
