### ISSUE TITLE
In tabs translations are not used

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#104]
Here the translation is not updated:
![controlsnotautoupdated](https://cloud.githubusercontent.com/assets/11966684/16241598/a790cec2-37ee-11e6-8434-f0b8d5d4d527.gif)

**Comment by jelhan** [comment]
It's a known bug in alpha5 and fixed in master. Known bugs are tracked in https://github.com/jelhan/croodle/releases/tag/v0.4.0-alpha5.
