### ISSUE TITLE
Tabs not translated

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#105]
Are you sure [this fix](https://github.com/jelhan/croodle/commit/7774e76551722716a5b38fca641a6803d57593b1) was successful?

Because on https://croodle.jhanschke.de, where I was said it uses the latest dev version, it still appears like this:
![croodletranslationissue](https://cloud.githubusercontent.com/assets/11966684/16241692/2e63bec8-37ef-11e6-9cd8-78a4efb20026.png)

**Comment by jelhan** [comment]
https://croodle.jhanschke.de running last pre-release (alpha5) not current master. 7774e76551722716a5b38fca641a6803d57593b1 was after alpha5. So everything should be fine. Please reopen if bug still occurs in current master or next pre-release.
