### ISSUE TITLE
[UI] Two scrollbars?

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#106]
Do we really need two (synchronous) scrollbars in the evaluation?

![twoscrollbars](https://cloud.githubusercontent.com/assets/11966684/16242352/547eb128-37f2-11e6-9358-a5edac4c38ad.png)

This looks a bit confusing...

**Comment by jelhan** [comment]
It's meant to help if table height is greater than window height:
![roodle20160820223126](https://cloud.githubusercontent.com/assets/4965703/17833733/38cccf38-6726-11e6-8f97-20218ba8dd79.gif)

But really need a sticky first column (name) in these cases also. #11

**Comment by jelhan** [comment]
Closing for now. But feel free to reopen if you have any suggestions on these part.

**Comment by rugk** [comment]
Your gif is a bit small, but I understand what you mean.
However I think you might hide the additional scrollbar if there are - say - only 5 entries. Could you just show them if there is need to?

I cannot reopen this issue by myself BTW if a maintainer closes it.

**Comment by jelhan** [comment]
> However I think you might hide the additional scrollbar if there are - say - only 5 entries. Could you just show them if there is need to?
Yeah, couple it with sticky table header might be a good idea. Will reopen. 

> I cannot reopen this issue by myself BTW if a maintainer closes it.
Oh, didn't know that.

**Comment by jelhan** [comment]
Closing this one as second scrollbar was removed by #164.
