### ISSUE TITLE
What about using Greenkeeper?

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#107]
It can help you to keep your npm dependencies updated.

See https://greenkeeper.io/ for more details.

@greenkeeperio

**Comment by jelhan** [comment]
Hadn't enough spare time yet to fix all deprecations in ember.js 1.13. I guess greenkeeper would not help with that one. ;-)

Also I'm not convinced of the way greenkeeper is integrated in ci and notifies about dependencie updates. It tends to blow up PR list.

**Comment by rugk** [comment]
An alternative is https://david-dm.org/. It shows you only a warning when your outdated dependencies have known security vulnerabilities.

**Comment by jelhan** [comment]
da0cf4096cb030dd2d7c4c5439491c7f0f17895b
