### ISSUE TITLE
Make it easier to move data dir around/change path

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#109]
Currently one has to edit two files (cron.php and index.php) if one wants to use another path for the `data` dir.

However as it is now required to protect the data dir, you should make it easier to configure the path of it, so that one can easily move it to another folder, which is not accessible by the web server. This is the best (and easiest) way to protect this folder.

An example on how this can be done, can be seen [here](https://github.com/PrivateBin/PrivateBin/blob/master/index.php#L13-L18), where there is clearly differentiated between a public folder and a private folder.

**Comment by jelhan** [comment]
Definitely a must have. But I don't like to mess up code and configuration like PrivateBin does. I think I will go for an `config.php` inside `api/` folder which exports an associative array and could be included by `index.php` and `cron.php`.

**Comment by rugk** [comment]
Yeah that's a good idea.
