### ISSUE TITLE
Undefined offset in cron.php

### ISSUE THREAD

**Issue by t2d** [jelhan/croodle#111]
```
$ php /var/www/www.systemli.org/croodle/api/cron.php
PHP Notice:  Undefined offset: 1 in /var/www/www.systemli.org/croodle/api/cron.php on line 18
```
v0.4.0

**Comment by jelhan** [comment]
Released [v0.4.1](https://github.com/jelhan/croodle/releases/tag/v0.4.1) including the fix.

**Comment by t2d** [comment]
the fix is not included in v.0.4.1

**Comment by jelhan** [comment]
Autsch. Wrong build was attached. It was another version (`0.4.0+6653da8e`) and not a development build. Uploaded the correct build. I'm sorry about that one.
