### ISSUE TITLE
Prevent referrer from being send

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#113]
See
* https://w3c.github.io/webappsec-referrer-policy/
* http://caniuse.com/#feat=referrer-policy

You can use it in HTML (`<meta name="referrer" content="no-referrer">`) or as [a HTTP header](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header). However the HTTP header version is not yet supported very much in browsers.

**Comment by jelhan** [comment]
Good catch. What about addressing it in #114 also?
