### ISSUE TITLE
24 hours displayed instead AM/PM

### ISSUE THREAD

**Issue by petrk94** [jelhan/croodle#124]
Hello,

I would like to know, whether there are some settings to change the time from AM/PM to 24h time format?
Is croodle even working with timezone differences? Like I want to make a online meeting in Berlin, but a friend is in Mexico, does it would work too??
Hope for an answer, Thanks.

**Comment by jelhan** [comment]
Did you selected a local which isn't english? _Deutsch_ and _español_ should use a 24 hours time format.

Time zones should also been handled. If you create a poll in one time zone and a user opens it in another time zone he is asked if his time zone or the one the poll got created in should be used. Just create a poll, manipulate your time zone and open it again to verify.

If you face any bug please report back.

**Comment by petrk94** [comment]
thanks for the fast answer.
yes I have tried and works fine, sorry for bother with that ^^
