### ISSUE TITLE
Add addtional information to evaluation

### ISSUE THREAD

**Issue by xshadow** [jelhan/croodle#125]
If you look at the evaluation you get information of how many people have time: 

> 
> The preferred dates are
> 
>     Saturday, April 1, 2017.
>     3 people have time. 

It would be a good information to so how many people out of all participants are able to join. Such as: 

> 
> The preferred dates are
> 
>     Saturday, April 1, 2017.
>     3 people out 5 have time.

**Comment by jelhan** [comment]
Sorry for not replying back earlier.

The number of participants is available just above the prefer date:

> 2 people participated in the poll.
> 
> The preferred dates are
> 
> - Monday, April 8, 2019. 
>   One person has time. One person does not have time.
> - Tuesday, April 9, 2019.
>   One person has time. One person does not have time.
> 
> The last person a few seconds ago attended.

What would be the benefit of repeating that information?
