### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) : /api/index.php/polls

### ISSUE THREAD

**Issue by deltatree** [jelhan/croodle#129]
![image](https://user-images.githubusercontent.com/6955880/28153542-35073c54-67a6-11e7-975d-3da34a625a39.png)

Using the current release - what is missing?

**Comment by jelhan** [comment]
Could you give some information about your environment? An request to `/api/index.php/polls` should be handled by `/api/index.php` and `/polls` should be passed to PHP script as `PATH_INFO`.  It should work with defaults of nginx and apache running on debian. Also have a look here: #92

**Comment by deltatree** [comment]
I'm pushing it to a cloudfoundry environment using the php_buildpack (php_buildpack-cached-v4.3.37.zip).
I tried httpd and nginx and for both I'm getting this error.
If I adapt the index.php catchall "return $c['response']->withStatus(404);" with some static stuff - I'm getting  the static stuff ... so all $app->post hooks are not recognizing that they are responsible for that request.

**Comment by jelhan** [comment]
This sounds like a configuration issue concerning path. You could dump `$request->getUri()` and `$request->getMethod()` values to see if web server passes correct values to php.

**Comment by deltatree** [comment]
solved: https://github.com/cloudfoundry/php-buildpack/issues/216
It is a bug in the php_buildpack - i've update to the current master and it is working ...

thanks a lot for your help :-)
