### ISSUE TITLE
Set Content Security Policy

### ISSUE THREAD

**Issue by t2d** [jelhan/croodle#144]
> Content Security Policy is an effective measure to protect your site from XSS attacks. By whitelisting sources of approved content, you can prevent the browser from loading malicious assets.

https://scotthelme.co.uk/content-security-policy-an-introduction/

**Comment by jelhan** [comment]
Could you please elaborate a little bit more, what changes need to be done? Setting up a strict content security policy (CSP) [is already recommended in readme](https://github.com/jelhan/croodle#webserver-configuration). Recommended CSP is provided in [/public/.htaccess](https://github.com/jelhan/croodle/blob/master/public/.htaccess). I don't think it could be stricter. [ember-content-security-policy](https://github.com/rwjblue/ember-cli-content-security-policy) is [configured to use this strict rules](https://github.com/jelhan/croodle/blob/master/config/environment.js#L16-L25) in development and testing.

**Comment by t2d** [comment]
I'm very sorry. I wasn't reading properly. The CSP ist really strict. Thank you, great job.
