### ISSUE TITLE
croodle selects the wrong most preferred date

### ISSUE THREAD

**Issue by hj-beckers** [jelhan/croodle#145]
If you look at the "bevorzugten Termine" (most preferred dates) croodle suggests Donnerstag 11:00/11:30 (3 ja/yes). But if you look at "Teilnehmende und ihre Antworten" (participants and their answers) there are 4 ja/yes for Freitag 11:00?

[croodle_Fehler.pdf](https://github.com/jelhan/croodle/files/1966866/croodle_Fehler.pdf)

**Comment by jelhan** [comment]
Sorry for not replying back earlier. Didn't had much time to work on this project the last year.

Croodle does not only count the _yes_ (ja) answers to determine most preferred dates. It takes also _no_ (nein) and _maybe_ (vielleicht) into account. It calculates points for each option. The option with most points wins. A _yes_ adds 2 points, a _maybe_ adds 1 point and a _no_ substracts 2 points. If user hasn't provided an answer for that option, it's ignored. https://github.com/jelhan/croodle/blob/bb160cc503e89bf756401f0b28cf3ef53c749e44/app/components/poll-evaluation-summary.js#L41-L53

This logic is maybe to complex and definitely not transparent to end user as it's documented nowhere. Will keep this issue open to track that one.

**Comment by jelhan** [comment]
Feature will be removed by #366.
