### ISSUE TITLE
[Feature Request] Single Date Choise

### ISSUE THREAD

**Issue by tasmo** [jelhan/croodle#175]
To find a date it is necessary to set a choice for every single day - whether "yes", "no" or "maybe".
This is slightly annoying to find different, non-overlapping dates for different people in a wide date range.

**Comment by jelhan** [comment]
Thanks for reporting that usability issue. If I get you right, it's the same problem as described in #142 but a different solution, isn't it?

**Comment by tasmo** [comment]
@jelhan Yes, seems to be similar. I would be happy with either or.

**Comment by jelhan** [comment]
Closing in favor of #142
