### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ced455** [jelhan/croodle#197]
Hello, do you have any full documentation to use the croodle API ?
i would like to be able to create poll automatically and get the link

This is for online esport tournament scheduling between players

**Comment by jelhan** [comment]
There isn't an API documentation but you could use the API acceptance tests as a starting point: https://github.com/jelhan/croodle/tree/master/api/tests/api

Values should be encrypted using `sjcl.encrypt()`. You could find encryption integration here: https://github.com/jelhan/croodle/blob/master/app/services/encryption.js I would not recommend to use another library as I expect configuring it to be compatible with [sjcl](http://bitwiseshiftleft.github.io/sjcl/) defaults will be very difficult.

You should make sure that random values are used to generate the encryption key and that it's not leaked to any third party.

**Comment by ced455** [comment]
Sound good,
Any way i can help to add french in app ?
the js file is not easy to edit at all :)

**Comment by jelhan** [comment]
> Any way i can help to add french in app ?
> the js file is not easy to edit at all :)

Unfortunately there isn't than editing the JavaScript source files. Haven't done it my own for a long time but if I remember correctly these are the required steps:

1. Determine the locale code for the language that should be added (e.g. `fr` for french).
2. Copy the folder `/app/locales/en` to `/app/locales/xx` where `xx` is the locale code.
3. Add an entry to `/app/locales/meta.js` for your new locale.
4. Translate the texts by editing the `translations.js` file in the locale folder created in step 2.

If you want to review your translations, you need to setup your environment for local development.

**Comment by jelhan** [comment]
Closed in favor of #221
