### ISSUE TITLE
[suggestion] dudle like horizontal tables for polls

### ISSUE THREAD

**Issue by besendorf** [jelhan/croodle#210]
What really keeps me the most from using croodle more often is the layout of the poll. It takes up a lot of display size and is very unclear.
Also a lot of horizontal space is wasted because most screens are wider than high.
Suggestion would be to use a calender like horizontal table like doodle and dudle are doing (see Screenshot)
![Screenshot_dudle](https://user-images.githubusercontent.com/26350155/59022078-67fcf080-884d-11e9-803c-edf2ec767e72.png)

**Comment by jelhan** [comment]
@besendorf, thanks for your input. Working with @sappor0 on an incremental redesign of Croodle and had discussed similar thoughts. I guess we are able to share a draft in the next weeks and would love to get some feedback. Will keep you in touch.

**Comment by jelhan** [comment]
Closed in favor of #366.
