### ISSUE TITLE
yarn install ???

### ISSUE THREAD

**Issue by azimut2000** [jelhan/croodle#226]
Hello
I'm tying to build this application with documentation; you said : 
```
git clone git@github.com:jelhan/croodle.git
cd croodle
yarn install
```
But it answer me : 
```
thierry@M83:~/Dev/doodle/croodle-master$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```
Don't you forget a file in source or is there another solution ?
Thank's
Thierry

**Comment by sappor0** [comment]
You probably have the wrong `yarn` command installed if you are on Linux.

Maybe this SO thread helps you https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by azimut2000** [comment]
> You probably have the wrong `yarn` command installed if you are on Linux.
> 
> Maybe this SO thread helps you https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

It work fine ! Thank's...
I only have again an other problem with proxy and SSL, but it's another things ;-) 
I close this ticket.
Thierry
