### ISSUE TITLE
Display timezone if my local one is different than original timezone

### ISSUE THREAD

**Issue by doobry-systemli** [jelhan/croodle#275]
It's nice that Croodle warns you about conflicting/different timezones. But based on feedback by international work groups it would help a lot if Croodle would do two more things:

1. Display original and my local timezone name in the infobox that warns you about the conflicting timezones. Something along the lines of "... should the dates be presented? <My time zone (GMT)> <Original time zone (UTC)>".
2. Display the name of selected timezone in input and result view. Something along the lines of "All times displayed in time zone UTC".

A dropdown menu that allows to dynamically switch between timezones (e.g. next to the languages selection menu) would be super nice as well.

**Comment by jelhan** [comment]
Closed in favor of #367.
