### ISSUE TITLE
API / Automation 

### ISSUE THREAD

**Issue by ced455** [jelhan/croodle#287]
Hello, i am looking for a system EXACTLY like croodle but i need to automate the creation of polls for the purpose of online esport tournament using the API or even something like zapier.

Do you know if croodle is compatible and if not do you think it would be a good idea to work on that ?

Thanks

**Comment by jelhan** [comment]
This question sounds very similar as the one asked by yourself in #197. Could you please elaborate what additional information you need?

**Comment by ced455** [comment]
sorry about that it was a long time i totaly forgot.
I need to get back into it but my knowledge is extremly limited :)
