### ISSUE TITLE
Spanish translation of "times must be unique"

### ISSUE THREAD

**Issue by doobry-systemli** [jelhan/croodle#311]
A spanish user reported back that the spanish translation "Horarios debe de ser único" (english string "Times must be explicit") doesn't make sense to her. According to her, the spanish translation "único" is confusing.

Her proposal would be to change the string to "Horas deben ser explícitas".

I had a quick look at `app/locales/es/translations.js` and saw that the string is splitted. But probably it would be enough to change `unique: '{{description}} debe de ser único` to `unique: '{{description}} deben ser explícitas`.

Please note that I don't speak spanish and cannot comment on her suggestion.

**Comment by jelhan** [comment]
Seems to make sense but I also don't speak any Spanish. @j0rgeSD I think you had provided the initial translation as part of #134. Does this change makes sense to you?
