### ISSUE TITLE
The poll could not be saved. Please try again in a few seconds.

### ISSUE THREAD

**Issue by SimpelMe** [jelhan/croodle#349]
Took the latest release and put it in folder "croodle" on my server.
"croodle" and "data" are 755.
Everything seems working but if I want save I get the message: "The poll could not be saved. Please try again in a few seconds."

Suggestions?

**Comment by jelhan** [comment]
Any additional information available in web server logs? Did you verified that the user used to execute the PHP script owns the `data` directory? Otherwise `755` is to restrict. It must have write access to set directory. You could quickly verify by changing the permissions to `777` but I would not recommend to leave it like this.

**Comment by SimpelMe** [comment]
Even if both folders are set to 777 this error occures.
It is an nginx.
If there are log files I can't grab them.

**Comment by SimpelMe** [comment]
I can set debugging in config.php to
` 'debug' => getenv('CROODLE__DEBUG') ?: true`
But where is the debugging output?

**Comment by SimpelMe** [comment]
Console in Chrome says:
`vendor-699c91804e8c881fe195a7977b3e0b4b.js:6303 POST /croodle/api/index.php/polls 404`

**Comment by jelhan** [comment]
You need to make sure that all requests to `/api/index.php` are handled by the corresponding file. You might want to compare your nginx configuration with the ones provided in #92 and #343.

**Comment by jelhan** [comment]
@SimpelMe Did you were able to solve the issue? If so, please share with us the solution. If not, please share the web server configuration.

**Comment by pietsch** [comment]
Silly me just had the same problem using Apache. Turns out I had forgotten to install PHP.

**Comment by jelhan** [comment]
@pietsch Thanks for sharing what solved the issue for you. Assuming that the issue is solved for @SimpelMe as well.
