### ISSUE TITLE
[master] Broken self-link in translations.js

### ISSUE THREAD

**Issue by hartwork** [jelhan/croodle#353]
Hi!

I ran into a broken link that seems cause by use of quote characters incompatible to HTML, see here `<a href=’https://github.com/jelhan/croodle’>GitHub</a>` at https://github.com/jelhan/croodle/blob/master/app/locales/en/translations.js#L66 . This causes broken links like https://www.systemli.org/poll/%E2%80%99https://github.com/jelhan/croodle%E2%80%99 in installations.

Best, Sebastian

**Comment by jelhan** [comment]
Thanks a lot for reporting this one. It has been fixed in #355. Will try to bundle a new release soon.

**Comment by hartwork** [comment]
Cool, thank you!
