### ISSUE TITLE
help with changes croodle-*.js

### ISSUE THREAD

**Issue by gluehbirne123** [jelhan/croodle#396]
Hi,

i built the files on my own and get it work in xampp. i have to change some spelling in the croodle-*.js - after that it is not working anymore.

for sure the sha256 and sha512 value is wrong now, but i could not figure out how to make a new, because if i do shasum of the old file i get another value as in index.html written.

any advice how this works together? thanks in advance

**Comment by jelhan** [comment]
Hello.

> i built the files on my own and get it work in xampp. i have to change some spelling in the croodle-*.js

Why are you modifying the build output and not the original source code? Especially if you are already doing a custom build?
 
> for sure the sha256 and sha512 value is wrong now, but i could not figure out how to make a new, because if i do shasum of the old file i get another value as in index.html written.
>
> any advice how this works together? thanks in advance

The [MDN article about Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) contains examples how to generate the hash. But I would strongly recommend to modify the source code _before_ the build (input) and not the build _output_.

**Comment by jelhan** [comment]
Did you found a working solution for your use case?
