### ISSUE TITLE
Add french

### ISSUE THREAD

**Issue by sharkyiwc** [jelhan/croodle#409]
Hi,

Sorry for my lack of experience on Github, I will train on the use of GIT.
In the meantime I am trying to submit the French translation of the application.
I am trying to compile to test, but there I am missing predures.

Thanks for your work

[fr.zip](https://github.com/jelhan/croodle/files/4655369/fr.zip)

**Comment by sharkyiwc** [comment]
I have make a fork and update french file
comma in text with ''

**Comment by jelhan** [comment]
Hello @sharkyiwc,

thanks a lot for providing french translations!

> Sorry for my lack of experience on Github, I will train on the use of GIT.

I don't think it's your fault. You shouldn't need to know teach yourself how to use git, just to improve Croodle's translations. This is an unnecessary blocker. I'm planning to make working on the translations easier but haven't found the time yet to do so. It's tracked in #201.

#408 looks good to me as a starting point. Why did you closed it?

I think we can use that pull request to get the work in. To do so we would need to do this steps:

1. Reopen the pull request on GitHub.
2. Update the `translations/fr.yml` with the latest translations if it's not the latest version.
3. Register the new local in `app/locales/meta.js`.

If I didn't missed something it should be working afterwards. Do you want to try it yourself? Or should I take over? If so: Where do I find the latest version of the translation?

Best

**Comment by sharkyiwc** [comment]
Hi,

I did a forks and I'm working on this version so as not to make too many mistakes on your version
https://github.com/sharkyiwc/croodle

I did not understand where the yml file was after compilation, in the version usable on a site ...
In the git, everything found;)

And I don't know how to compile to test, however I work with Linux and Windows. But things still elude me in development.

Best

**Comment by jelhan** [comment]
> And I don't know how to compile to test, however I work with Linux and Windows.

I'm sorry that the repository is still missing good contribution documentation. (#221) To build and test locally you should follow these steps:

1. Install git, node.js, yarn and php.
2. Clone the repository (or your fork).
3. Run `yarn install` in the folder to which you have cloned the repository.
4. Run `ember serve` in the same folder.
5. Open http://locahost:4200 in a browser of your choice.

This starts Croodle with a mocking API. So don't be confused if your poll disappears on refresh. This is expected.

If you want to run the test suite execute `yarn test` instead of `ember serve` or open http://localhost:4200/tests in a browser of your choice.

**Comment by sharkyiwc** [comment]
Hi,
I am stuck in step 4. ember not know
Test on Windows and Linux
On linux try install ember but is a game ;)
npm 6.14.5
node 14.3.0  after warning downgrade 13.14.0

4. you want say run `yarn ember serve`
> WARNING: Node v14.3.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
> The `no-bare-strings` rule must be configured when using a localization framework (`ember-intl`). To prevent this warning, add the following to your `.template-lintrc.js`:

Not work with node 13 too
> WARNING: Node v13.14.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
> The `no-bare-strings` rule must be configured when using a localization framework (`ember-intl`). To prevent this warning, add the following to your `.template-lintrc.js`:
> 
>   rules: {
>     'no-bare-strings': true
>   }
> internal/fs/watchers.js:177
>     throw error;
>     ^
> 
> Error: ENOSPC: System limit for number of file watchers reached, watch '/home/me/github/croodle/croodle/node_modules/optimist/node_modules/minimist/example'
>     at FSWatcher.<computed> (internal/fs/watchers.js:169:26)
>     at Object.watch (fs.js:1435:34)
>     at NodeWatcher.watchdir (/home/me/github/croodle/croodle/node_modules/sane/src/node_watcher.js:159:22)
>     at Walker.<anonymous> (/home/me/github/croodle/croodle/node_modules/sane/src/common.js:109:31)
>     at Walker.emit (events.js:315:20)
>     at Walker.EventEmitter.emit (domain.js:485:12)
>     at /home/me/github/croodle/croodle/node_modules/walker/lib/walker.js:69:16
>     at FSReqCallback.oncomplete (fs.js:159:23) {
>   errno: -28,
>   syscall: 'watch',
>   code: 'ENOSPC',
>   path: '/home/me/github/croodle/croodle/node_modules/optimist/node_modules/minimist/example',
>   filename: '/home/me/github/croodle/croodle/node_modules/optimist/node_modules/minimist/example'
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

There is a lot of dependence that I do not master for good development.

**Comment by jelhan** [comment]
To be honest I'm not sure what's happening there.

The OS has a limit of files which could be watched in parallel (`fs.inotify.max_user_watches`). The error message tells us that the node process tried to watch another file but this limit was already reached. But the error seems to be more like a syndrome than the root issue. If I read it correctly, it tried to watch a file in `node_modules/`. But it should not watch files in `node_modules`.

I'm also a little bit surprised by the path `/home/me/github/croodle/croodle/`. Did you double-checked that you haven't cloned the repository twice? You might have another folder `croodle` within the repository - and that one could cause the error if you try to run `ember serve` (or `ember build` in ``/home/me/github/croodle`).

**Comment by sharkyiwc** [comment]
Hi,

The path is local clone repository of my Github clone
I created the folder by not passing who created it. This is the reason that there is a sub-folder of the same name.
Lack of Github experience!

I am using Visual Studio Code with the terminal and it is well executed from the local root

Thank you for assisting me with this procedure.

**Comment by jelhan** [comment]
@sharkyiwc I have merged the french translations provided by you in the first post in #425. I'm very sorry that this has been taken so long. I hope I haven't demotivated you too much. Thanks a lot for contributing!

Would appreciate if you can maintain the franch translations as I don't speak french. Especially updating them to accommodate changes in the user interface when needed.
