### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by demlak** [jelhan/croodle#418]
Ever thought about LDAP connection to auto-get and bind to users?

**Comment by jelhan** [comment]
Hello @demlak.

I'm not sure how LDAP support would fit with the goals of Croodle and its current feature set. Authentication is not a feature considered for Croodle at all (yet).

Are you aware of [Dudle](https://github.com/kellerben/dudle/)? If I recall correctly Dudle provides authentication. Not sure if it has LDAP support.

**Comment by demlak** [comment]
Hey.. thx a lot.. i would prefer croodle MUCH more, because of simplicity for the users =)

**Comment by demlak** [comment]
Hey.. thx a lot.. i would prefer croodle MUCH more, because of simplicity for the users =)

**Comment by jelhan** [comment]
I'm happy to hear but I fear authentication is out of scope for now and foreseeable future.
