### ISSUE TITLE
[Layout][#/create/options] -  Set headline in box for dates

### ISSUE THREAD

**Issue by xshadow** [jelhan/croodle#43]
Missing headline in date choosing box

**Comment by jelhan** [comment]
I thought a calendar is self-explanatory. Do you really think a headline is necessary?

**Comment by xshadow** [comment]
Everywhere else is a kind of headline , so there should be one too. It's good for the user experience and does not interrupt your view / eye experience.

**Comment by jelhan** [comment]
I tried adding a headline but it looks confussing to me. I attached a screenshot.
![headline-calendar](https://cloud.githubusercontent.com/assets/4965703/5816319/0f4621e0-a09f-11e4-964f-1768ad7ab244.png)

**Comment by jelhan** [comment]
#76
