### ISSUE TITLE
how to make croodle work

### ISSUE THREAD

**Issue by NiklasLazinbee** [jelhan/croodle#564]
I have uploaded the latest release to my server. When I navigate to /app/index.html I get the error message that vendor.js, croodle.css, vendor.js, ... cannot be loaded. But in the whole release these files do not exist. Probably I am doing something fundamentally wrong?

**Comment by jelhan** [comment]
It sounds as if you have uploaded the source code and not the build. You can find a build for latest release here: https://github.com/jelhan/croodle/releases/download/v0.6.2/croodle-v0.6.2.tar.gz

**Comment by NiklasLazinbee** [comment]
Thank you for the tip. Croodle now works for me. A great application!
