### ISSUE TITLE
module for nixos

### ISSUE THREAD

**Issue by jboynyc** [jelhan/croodle#570]
FYI, I wrote a module for NixOS, which makes running Croodle as easy as adding `services.croodle.enable = true` to a system configuration. 

https://gitlab.com/d12n/server-config/-/commit/caf788b2bdf866b30a9d960763a028b20cb54286

**Comment by jelhan** [comment]
Thanks a lot. Seeing others engaging in Croodle development is motivating to pick it up again myself!

Are you open to pull it out into a reusable library? And is that even possible from a technical point of view? If so, and if you are willing to maintain it, I'm open adding a link to it in deployment docs.

**Comment by jboynyc** [comment]
Happy to hear it's encouraging. Thanks for your work on Croodle!

I could try upstreaming the module, then it would be available to all nixos users. I'll see if I have bandwidth in the coming weeks to open a PR in nixpkgs. If so, I'll post it here so you can keep tabs on it.

**Comment by jboynyc** [comment]
OK, I managed to put a PR together faster than anticipated: https://github.com/NixOS/nixpkgs/pull/242289
