### ISSUE TITLE
[Poll] - Input / Name row is compressed if poll is large 

### ISSUE THREAD

**Issue by xshadow** [jelhan/croodle#59]
Please do not shorten the Name Input.

At the moment the row depends on the length of the entered nick names. If nothing was entered is the bar is compressed. 

Suggested behaviour: 
If there was no user input, then this row should have a fixed width.

If there was input, the row should be as long as the longest entered name.

**Comment by jelhan** [comment]
Closed in favour of #76 and shouldn't be an issue any more since 01f9b6e61f4ccd79bded72e9783cc3fe3aae4030
