### ISSUE TITLE
[Poll] - limit displayed answers posibilities in large polls

### ISSUE THREAD

**Issue by xshadow** [jelhan/croodle#60]
It would if only a limited count of answer possibilities are displayed in large polls.

In polls with more then X (8) possible answers , display only Y ( 3 ) answer , and enable "show all possibilities" button - which displays the rest ( with that nasty scroll bar :) )

**Comment by jelhan** [comment]
Since #76 it's only an issue for poll/participation detail view. Keeping open until we have discussed this in detail.

**Comment by jelhan** [comment]
Closed in favor of #366
