### ISSUE TITLE
Add version string

### ISSUE THREAD

**Issue by t2d** [jelhan/croodle#65]
Maybe on index.html or just a VERSION file

**Comment by jelhan** [comment]
Support for `ember-cli-build-info` was dropped and addon marked as deprecated. `ember-cli-app-version` is recommended instead. There wasn't a release yet before adding `ember-cli-build-info`. Reverted commit and reopened this issue.

**Comment by t2d** [comment]
Sorry, to bring this up again.
The tag of your latest release is "v0.3.0".
But ember writes "v0.3-0" to your index.html.
Can we please align these?

**Comment by jelhan** [comment]
`ember-cli-build-info` seems to have a lot of bugs... Hope I fixed all of them. Should be fine after eb798a3c4c1961e191f7dede7a818e384450cffd.
