### ISSUE TITLE
Kindly provide the dist directory

### ISSUE THREAD

**Issue by axilleas** [jelhan/croodle#70]
Is there any reason not to also provide the `dist/` directory that gets built in the end?

It would be really helpful.

**Comment by jelhan** [comment]
There is a production built for every release here: https://github.com/jelhan/croodle/releases I don't like including `dist/` directory in repository. If you realy like to use or play around with development branch you should build it yourself.

**Comment by axilleas** [comment]
Oh, I wasn't aware of this, thanks!
