### ISSUE TITLE
Use Prettier for Glimmer templates

### ISSUE THREAD

**Issue by jelhan** [jelhan/croodle#702]
We should adopt Prettier for Glimmer templates to ensure consistent formatting in templates as we do in JavaScript.

**Comment by Ayush-Vish** [comment]
@jelhan  I would like to work on this issue , Please assign it to me.

**Comment by jelhan** [comment]
> @jelhan I would like to work on this issue , Please assign it to me.

I assigned the ticket to you. Thanks a lot for your support!

Not sure if you are familiar with Ember ecosystem. In case not, [ember-template-lint-plugin-prettier](https://github.com/ember-template-lint/ember-template-lint-plugin-prettier) is a good starting point. Let me know if you have any questions.

**Comment by jelhan** [comment]
@Ayush-Vish: Did you had time looking into this one?

**Comment by Ayush-Vish** [comment]
@jelhan  Sorry for the delay, but I am busy with something else.
