### ISSUE TITLE
Whats the idea behind "Allow free text" in date poll?

### ISSUE THREAD

**Issue by xshadow** [jelhan/croodle#75]
Whats the idea behind "Allow free text" in date poll?

Yes, no / Yes ,no, maybe should be enough.

**Comment by jelhan** [comment]
There might be use cases like "What partys could you recommend for the days we stay in Berlin?". User may enter a party/club name per day.

**Comment by xshadow** [comment]
Then I think it should be a/another poll - it doesn't make sense to me, when deciding on dates or meeting times
