### ISSUE TITLE
redesign User Interface

### ISSUE THREAD

**Issue by jelhan** [jelhan/croodle#76]
Track changes discussed in our last meeting.
# general
- [x] use fixed-width container instead of fluid one (3e92fa8c87d92644520a6333ec26e6dfc263bbdc)
- [ ] simplify answers; provide more complex answer possibilities via expert options (another issue will be added)
# /poll
- [x] use poll title as page title (8441c92295eed20a9c3a80b93749492519e9f60d)
- [x] routable tabs in poll view for participation and evaluation (858b75e54330e35dd0f4e128863e19a3108f5e71)
## /poll/participation
- [x] extract participation form from participants table and make it a "normal" form instead of inline available via participation tab (01f9b6e61f4ccd79bded72e9783cc3fe3aae4030)
## /poll/evaluation
- [x] show a evaluation summary
- [x] provide bar chart for evaluation
- [x] move participants table to evaluation table
# /create
- [ ] start poll creation on index page; provide two button (find a date; make a poll) there; `/create/index` is skipped when these buttons are used and only used if someone links directly to `/create`
- [x] provide status bar to indicate steps of poll creation wizard (3d251bc9fb924441e87dfb548ea853b8d65c7d01)
- [x] `next` / `skip` and `back` button on all pages (d8db29ecd96ab207ec7c6cec2d6b1b779116d810)
## /create/options (find a date)
- [ ] show a list of selected dates and provide a delete button there as well
- [ ] provide a legend for calendar
- [x] show two month in calendar
## /create/options (make a poll)
- [x] add / delete buttons next to option input fields (ca387848edc9a1a3a6f07b70bda79285db06fa99)
- [ ] reorder options by reordering input fields; checkout https://github.com/jgwhite/ember-sortable therefore
## /create/options-datetimes (find a date only)
- [x] always ask if times should be specified for dates
- [x] use normal form instead of table (3563e41913ed2817e28618e02c9026ccf65aec1f)
- [ ] "adopt times for all other dates"-button next to first date
- [x] add / delete buttons next to time input fields (same as /create/options for make a poll) (3563e41913ed2817e28618e02c9026ccf65aec1f)
## /create/settings
- [ ] show preview of poll
- [ ] ask if everything is fine or if user likes to configure poll with expert options

**Comment by xshadow** [comment]
Please change the calendar order to Monday --> Sunday. By now its Sunday --> Saturday. That is kind of confusing

**Comment by jelhan** [comment]
@xshadow moved to a separate issue: #89

**Comment by jelhan** [comment]
@sappor0, I'm quite sure you saw this issue but just wanted to make sure. :smile: Will close it now as it's outdated by our last discussions.
