### ISSUE TITLE
Make it 100% CSP compatible

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#90]
Nice you already advice users to use CSP and use a quite strong policy, but it would be nice if you could also remove the [unsafe directives](https://scotthelme.co.uk/content-security-policy-an-introduction/#realworldlimitations). Because only without `'unsafe-eval'` and `'unsafe-inline'` (for CSS) real XSS protection can be provided.

Also note that for PHP there is [a CSP framework](https://github.com/paragonie/csp-builder), which you can use.

**Comment by jelhan** [comment]
Would love to drop them. But currently they are required by dependencies.

`'unsafe-eval'` is required by Chart.js 1.x. After https://github.com/aomran/ember-cli-chart/pull/54 is merged we could update to Chart.js 2.x and get rid of it.

`style-src: 'unsafe-inline`' is required by webshim polyfill and Modenizr (https://github.com/Modernizr/Modernizr/issues/1262).
Webshim and Modenizr are only used for a better user experience in browsers which does not support input type `time`. Should definitely replaced them by a lightweight solution.

**Comment by jelhan** [comment]
CSP header must be send along with `index.html`. PHP is only used for API which is consumed via ajax. Dropped them from api a long time ago: https://github.com/jelhan/croodle/commit/eb24c47e6ac947537b080144bc1b5b048069012c

**Comment by rugk** [comment]
Okay, thanks for your information...

**Comment by jelhan** [comment]
webshim polyfill and Modenizr are removed but a small line to fix validation icon position causes another CSP violation if `unsafe-inline` is not allowed for `style-src`: https://github.com/kaliber5/ember-bootstrap/pull/98#discussion_r66586065

**Comment by jelhan** [comment]
Fixed CSP violation caused by ember-bootstrap by https://github.com/kaliber5/ember-bootstrap/pull/98/commits/01491ae11985687925bcbde786ed86860ca6af92 but noticed that [jquery.floatThead](https://github.com/mkoryak/floatThead) also requires `unsafe-inline`.

**Comment by jelhan** [comment]
`script-src: 'unsafe-eval'` has been removed by 2a75db530479051b52a6052fb3a2925b801751cd. `style-src: 'unsafe-inline'` could be removed after https://github.com/mkoryak/floatThead/pull/321 has been made it's way into a stable release.

**Comment by rugk** [comment]
Awesome! :tada:
