### ISSUE TITLE
UX: Support tab key when creating poll

### ISSUE THREAD

**Issue by rugk** [jelhan/croodle#94]
Especially when entering the options for a poll it would be nice if one could just use tab to switch to the next option.
Currently this does not work and even shows an error message.

**Comment by jelhan** [comment]
Blocked by `autofocus` issue in ember.js: https://github.com/kaliber5/ember-bootstrap/issues/130

**Comment by rugk** [comment]
Your milestone is a bit outdated (you already released v0.5.4). Or is this issue already fixed?

**Comment by jelhan** [comment]
You are right. Tab key is already supported for creating a poll except for selection of days (calendar). You could also use tab key if participating in a poll. It landed in v0.5.0.
